# Generated by Django 3.1 on 2020-10-16 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201013_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
